#!/usr/bin/env node
/**
 * Make a fresh clone buildable: create any missing personal or generated data
 * file from its example (or an empty default). Never overwrites existing files.
 * Runs automatically before `dev` and `build`.
 */
import { copyFileSync, existsSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const data = (f) => join(root, "src", "data", f);

// Personal data you edit: copied from the checked-in example.
const fromExample = [
  ["me.example.ts", "me.ts"],
  ["certificates.example.json", "certificates.json"],
  ["lab-sites.example.json", "lab-sites.json"],
  ["repo-curation.example.json", "repo-curation.json"],
];

// Generated by scripts (fetch-repos, probe-deploys): start empty.
const generated = {
  "repos.json": { repos: [] },
  "deploy-status.json": {},
  "github-stats.json": { publicRepos: 0 },
  "vercel-sites.json": { sites: [] },
};

const created = [];
for (const [example, target] of fromExample) {
  if (!existsSync(data(target))) {
    copyFileSync(data(example), data(target));
    created.push(`src/data/${target} (from ${example})`);
  }
}
for (const [file, value] of Object.entries(generated)) {
  if (!existsSync(data(file))) {
    writeFileSync(data(file), JSON.stringify(value, null, 2) + "\n");
    created.push(`src/data/${file}`);
  }
}
if (!existsSync(join(root, "portfolio.config.json"))) {
  console.log("note: no portfolio.config.json; copy portfolio.config.example.json if you use the deploy or resume scripts.");
}
if (created.length) console.log(`init-data: created\n  ${created.join("\n  ")}`);
